name: CI
on:
  push:
    paths-ignore: [".github/**/*"]
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: windows-latest
    
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: .NET Setup
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Fetch submodules
      run: git submodule update --init --recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Navigate to workspace
      run: cd $GITHUB_WORKSPACE

    - name: Restore packages
      run: nuget restore UAssetGUI.sln

    - name: Build All
      run: msbuild UAssetGUI.sln /p:Configuration=Release

    - name: Build Publish Binary
      run: dotnet publish --sc false -c Release -r win-x64 -p:PublishSingleFile=true -o ./build ./UAssetGUI/UAssetGUI.csproj

    - name: Get Short SHA
      id: vars
      shell: bash
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Get Project Version
      uses: bbonkr/get-version-action@v1
      id: get_version
      with:
        project: './UAssetGUI/UAssetGUI.csproj'
        show_log_message: true

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.6.1
      with:
          name: UAssetGUI-${{ steps.get_version.outputs.version }}-${{ steps.vars.outputs.sha_short }}
          path: ./build/*.exe
    
    - name: Make Experimental Pre-Release
      uses: softprops/action-gh-release@v2
      with:
        prerelease: true        
        tag_name: experimental-latest
        name: UAssetGUI-${{ steps.get_version.outputs.version }}-${{ steps.vars.outputs.sha_short }}
        files: ./build/*.exe
